# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "IR-Labs"
    workspaces {
      name = "terragrunt-mgi-test-test" 
    }
  }
}
