# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# terraform {
#   backend "remote" {
#     hostname = "app.terraform.io"
#     organization = "IR-Labs"
#     workspaces {
#       name = "terragrunt-mgi-test-test" 
#     }
#   }
# }


terraform {
  # The configuration for this backend will be filled in by Terragrunt
  backend "s3" {}
}
