version: "3"
services:
    shinobi:
        image: shinobisystems/shinobi:dev
        container_name: Shinobi
        environment:
           - PLUGIN_KEYS={"Tensorflow":""}
           - SSL_ENABLED=false
        volumes:
           - /Users/lol/Shinobi/config:/config
           - /Users/lol/Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
           - /Users/lol/Shinobi/database:/var/lib/mysql
           - /Users/lol/Shinobi/videos:/home/Shinobi/videos
           - /Users/lol/Shinobi/plugins:/home/Shinobi/plugins
           - /dev/shm/Shinobi/streams:/dev/shm/streams
           - /etc/localtime:/etc/localtime:ro
        ports:
           - 8080:8080
        restart: unless-stopped

    shinobiplugintensorflow:
        image: shinobisystems/shinobi-tensorflow:latest
        container_name: shinobi-tensorflow
        environment:
          - PLUGIN_KEY=
          - PLUGIN_HOST=Shinobi
        volumes:
          - /Users/lol/Shinobi/docker-plugins/tensorflow:/config
        restart: unless-stopped
